# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{dioxide_rails}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jason Vasquez"]
  s.date = %q{2011-02-10}
  s.email = %q{admin@developertown.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "app/controllers/dioxide/api_controller.rb",
    "config/routes.rb",
    "lib/dioxide_rails.rb",
    "lib/dioxide_rails/handlers.rb",
    "lib/dioxide_rails/handlers/dioxide_handler.rb",
    "lib/dioxide_rails/rpc_request.rb",
    "lib/dioxide_rails/rpc_response.rb",
    "lib/engine.rb",
    "lib/rails/generators/dioxide_rails/dioxide_rails_generator.rb",
    "lib/rails/generators/dioxide_rails/templates/initializer.rb"
  ]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.0}
  s.summary = %q{Ruby On Rails implementation of the Dioxide RPC framework}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

